title: My Portfolio
#logo: /assets/img/headshot_circle.png
description: Thank you for reviewing my portfolio. As a mechanical engineering student at California State University Northridge, I offer a blend of academic knowledge and practical skills. My coursework covers thermodynamics, fluid mechanics, and materials science, while my ASME involvement has honed my CAD modeling, prototyping, and problem-solving abilities. I'm passionate about collaborative innovation and eager to tackle real-world engineering challenges to improve efficiency and sustainability.
#show_downloads: true
theme: jekyll-theme-minimal
